FROM ubuntu
RUN apt-get update
RUN apt-get install git

# Install GMP (NTL v10 requires it)
#RUN apt-get install libgmp3-dev

# Install NTL v6
RUN wget http://www.shoup.net/ntl/ntl-6.0.0.tar.gz
RUN tar xfs ntl-6.0.0.tar.gz
RUN cd ntl-6.0.0/src/
RUN ./configure
RUN make
RUN make check
RUN make install

# Compile fhe-si
RUN cd
RUN mkdir git
RUN cd git
RUN git clone git@github.com:dwu4/fhe-si.git
RUN cd fhe-si
RUN git reset --hard 85fb071747c3705ca374b6bce6329564be5cc7da # Make sure we are on the right version
RUN make

