FROM ubuntu
RUN apt-get update
RUN apt-get install git

# Install GMP (NTL requires it)
RUN apt-get install libgmp3-dev

# Install NTL v10
RUN wget http://www.shoup.net/ntl/ntl-10.5.0.tar.gz
RUN tar xfs ntl-10.5.0.tar.gz
RUN cd ntl-10.5.0/src/
RUN ./configure
RUN make
RUN make check
RUN make install

# Compile fhe-si
RUN cd
RUN mkdir git
RUN cd git
RUN git clone git@github.com:dwu4/fhe-si.git
RUN cd fhe-si
RUN git reset --hard 65a20d29066215bbd3addb054a2a37fe201b37e4 # Make sure we are on the right version
RUN make

